name: Asset Scraper

on:
    workflow_dispatch:
        inputs:
            start_card:
                description: "Start card index:"
                required: false
            end_card:
                description: "End card index"
                required: false
            start_gacha:
                description: "Start gacha index"
                required: false
            end_gacha:
                description: "End gacha index"
                required: false
permissions:
  contents: write

jobs:
    scrape_card:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12.5"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Scrape card images and information
              run: |
                echo "Scraping card images and collecting info from sekai.best and sekaipedia..."
                python card_scraper_script.py \
                --start_card ${{ github.event.inputs.start_card }} \
                --end_card ${{ github.event.inputs.end_card }} \
                --task "scrape card info"

            - name: Reorder card_metadata.json, generate individual card .json files
              run: |
                echo "Reordering card_metadata.json and generating individual card files..."
                python card_scraper_script.py \
                --start_card ${{ github.event.inputs.start_card }} \
                --end_card ${{ github.event.inputs.end_card }} \
                --task "reorder card info"

            - name: Commit and push results
              if: ${{ github.event.inputs.start_card != '' && github.event.inputs.end_card != '' }}
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Update scraped assets [skip ci]" || echo "No changes to commit"
                git push

    scrape_gacha:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12.5"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Scrape gacha information
              run: |
                echo "Collecting gacha info from sekai.best and sekaipedia..."
                python gacha_scraper_script.py \
                --start_gacha ${{ github.event.inputs.start_gacha }} \
                --end_gacha ${{ github.event.inputs.end_gacha }} \
                --task "scrape gacha info"
            
            - name: Reorder gacha_metadata.json, generate individual gacha .json files
              run: |
                echo "Reordering gacha_metadata.json and generating individual gacha files..."
                python gacha_scraper_script.py \
                --start_gacha ${{ github.event.inputs.start_gacha }} \
                --end_gacha ${{ github.event.inputs.end_gacha }} \
                --task "reorder gacha info"

            - name: Commit and push results
              if: ${{ github.event.inputs.start_gacha != '' && github.event.inputs.end_gacha != '' }}
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Update scraped assets [skip ci]" || echo "No changes to commit"
                git push
