name: Asset Scraper

on:
    workflow_dispatch:
        inputs:
            start_card:
                description: "Start card index:"
                required: true
            end_card:
                description: "End card index"
                required: true
            start_gacha:
                description: "Start gacha index"
                required: true
            end_gacha:
                description: "End gacha index"
                required: true
jobs:
    scrape_card:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12.5"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Scrape card images and information
              run: |
                echo "Scraping card images and collecting info from sekai.best and sekaipedia..."
                python card_scraper_script.py \
                --start_card ${{ github.event.inputs.start_id }} \
                --end_card ${{ github.event.inputs.end_id }} \
                --task "scrape card info"

            - name: Reorder card_metadata.json, generate individual card .json files
              run: |
                echo "Reordering card_metadata.json and generating individual card files..."
                python card_scraper_script.py \
                --start_card ${{ github.event.inputs.start_id }} \
                --end_card ${{ github.event.inputs.end_id }} \
                --task "reorder card info"

    scrape_gacha:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Scrape gacha information
              run: |
                    echo "Collecting gacha info from sekai.best and sekaipedia..."
